name = "okayy"
author = "tony"
version = "3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdab89e7f97de2cee9b059c69f4894f92b8b1a37680e1b8c9a3069b372e3f66f"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
