name = "okayy"
author = "tony"
version = "3.4.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41dfb89a2f7961f5534b657f9738d658d880467c3f34127ded8a3d7a25d9d52b"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
