name = "okayy"
author = "tony"
version = "3.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e3cf27293b862b9e32118c438503a475c39d1dcb8c6b501352573a44f2899a7"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
